use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct Plan {
    pub id: Uuid,
    pub name: String,
    pub slug: String,
    pub price: f64,
    pub annual_price: Option<f64>,
    pub side: String,
    pub max_custom_domains: Option<i32>,
    pub max_cards: Option<i32>,
    pub max_qr_codes: Option<i32>,
    pub max_action_buttons: Option<i32>,
    pub max_forms: Option<i32>,
    pub max_leads: Option<i32>,
    pub max_tags: Option<i32>,
    pub max_team_members: Option<i32>,
    pub max_ocr_scans: Option<i32>,
    pub has_webhooks: bool,
    pub has_api: bool,
    pub has_dual_routing: bool,
    pub has_mini_funnels: bool,
    pub has_card_gating: bool,
    pub has_remove_branding: bool,
    pub has_white_label: bool,
    pub has_multi_tenant: bool,
    pub has_analytics: bool,
    pub has_import_export: bool,
    pub billing_cycle: String,
    pub purchase_url: Option<String>,
    pub payment_provider: Option<String>,
    pub features: Option<serde_json::Value>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CreatePlanRequest {
    pub name: String,
    pub slug: String,
    pub price: f64,
    pub annual_price: Option<f64>,
    pub side: Option<String>,
    pub max_custom_domains: Option<i32>,
    pub max_cards: Option<i32>,
    pub max_qr_codes: Option<i32>,
    pub max_action_buttons: Option<i32>,
    pub max_forms: Option<i32>,
    pub max_leads: Option<i32>,
    pub max_tags: Option<i32>,
    pub max_team_members: Option<i32>,
    pub max_ocr_scans: Option<i32>,
    pub has_webhooks: Option<bool>,
    pub has_api: Option<bool>,
    pub has_dual_routing: Option<bool>,
    pub has_mini_funnels: Option<bool>,
    pub has_card_gating: Option<bool>,
    pub has_remove_branding: Option<bool>,
    pub has_white_label: Option<bool>,
    pub has_multi_tenant: Option<bool>,
    pub has_analytics: Option<bool>,
    pub has_import_export: Option<bool>,
    pub billing_cycle: Option<String>,
    pub purchase_url: Option<String>,
    pub payment_provider: Option<String>,
    pub features: Option<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UpdatePlanRequest {
    pub name: Option<String>,
    pub slug: Option<String>,
    pub price: Option<f64>,
    pub annual_price: Option<f64>,
    pub side: Option<String>,
    pub max_custom_domains: Option<i32>,
    pub max_cards: Option<i32>,
    pub max_qr_codes: Option<i32>,
    pub max_action_buttons: Option<i32>,
    pub max_forms: Option<i32>,
    pub max_leads: Option<i32>,
    pub max_tags: Option<i32>,
    pub max_team_members: Option<i32>,
    pub max_ocr_scans: Option<i32>,
    pub has_webhooks: Option<bool>,
    pub has_api: Option<bool>,
    pub has_dual_routing: Option<bool>,
    pub has_mini_funnels: Option<bool>,
    pub has_card_gating: Option<bool>,
    pub has_remove_branding: Option<bool>,
    pub has_white_label: Option<bool>,
    pub has_multi_tenant: Option<bool>,
    pub has_analytics: Option<bool>,
    pub has_import_export: Option<bool>,
    pub billing_cycle: Option<String>,
    pub purchase_url: Option<String>,
    pub payment_provider: Option<String>,
    pub features: Option<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize, FromRow)]
pub struct TenantPlanSubscription {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub plan_id: Uuid,
    pub start_date: NaiveDateTime,
    pub end_date: Option<NaiveDateTime>,
    pub status: String,
    pub created_at: NaiveDateTime,
}
